services:
  auth_service:
    build: ./auth_service
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./auth_service:/app

  data_entry_service:
    build: ./data_entry_service
    ports:
      - "5001:5001"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      mysql:
        condition: service_healthy
      auth_service:
        condition: service_started
    restart: unless-stopped

  analytics_service:
    build: ./analytics_service
    ports:
      - "5002:5002"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MONGO_URI=mongodb://mongodb:27017/
    depends_on:
      - mysql
      - mongodb

  results_service:
    build: ./results_service
    ports:
      - "5003:5003"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - mongodb
      - auth_service

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db

volumes:
  mysql_data:
  mongodb_data: