apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
spec:
  replicas: 2  # Start with 2 replicas for high availability
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
      - name: analytics-service
        image: cxxflame/analytics-service:latest  # Replace with your registry
        ports:
        - containerPort: 5002
        env:
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: mysql-password
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: mysql-database
        - name: MONGO_URI
          value: "mongodb://mongodb:27017/"
        - name: ANALYTICS_UPDATE_INTERVAL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: analytics-update-interval
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"