apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # Base64 encoded values
  mysql-root-password: cm9vdF9wYXNzd29yZA==     # root_password
  mysql-password: YXBwX3Bhc3N3b3Jk             # app_password
  secret-key: eW91ci12ZXJ5LXNlY3JldC1rZXktaGVyZQ==  # your-very-secret-key-here